// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkc5i1MxPLfRwP36PqzTs_lH9ZJBkVMho',
    appId: '1:341596777221:web:1253eabc7f220d745f256c',
    messagingSenderId: '341596777221',
    projectId: 'pigeons-fy2023',
    authDomain: 'pigeons-fy2023.firebaseapp.com',
    storageBucket: 'pigeons-fy2023.appspot.com',
    measurementId: 'G-BPCX8KVKMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnbZM9lRJqr3swCA7IIN66DhzhL6D3iK0',
    appId: '1:341596777221:android:d0150b24b58464665f256c',
    messagingSenderId: '341596777221',
    projectId: 'pigeons-fy2023',
    storageBucket: 'pigeons-fy2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4ZTmN7Vu51rTjzN6652Nwgmqqc1sRBF0',
    appId: '1:341596777221:ios:db74c7d82714e80d5f256c',
    messagingSenderId: '341596777221',
    projectId: 'pigeons-fy2023',
    storageBucket: 'pigeons-fy2023.appspot.com',
    iosClientId: '341596777221-a5mtncs3te70j3m77jb67h5iq11mqb1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.pigeons',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4ZTmN7Vu51rTjzN6652Nwgmqqc1sRBF0',
    appId: '1:341596777221:ios:db74c7d82714e80d5f256c',
    messagingSenderId: '341596777221',
    projectId: 'pigeons-fy2023',
    storageBucket: 'pigeons-fy2023.appspot.com',
    iosClientId: '341596777221-a5mtncs3te70j3m77jb67h5iq11mqb1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.pigeons',
  );
}
